DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS track_time_logs CASCADE;

CREATE TABLE IF NOT EXISTS directors
(
    director_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name       VARCHAR NOT NULL,
    director_birth_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name        VARCHAR NOT NULL,
    film_description VARCHAR NOT NULL,
    film_rating      REAL    NOT NULL,
    film_director_id BIGINT  NOT NULL,

    CONSTRAINT fk_film_producer FOREIGN KEY (film_director_id) REFERENCES directors (director_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS track_time_logs
(
    track_time_log_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_time_log_method_name        VARCHAR NOT NULL,
    track_time_log_method_args        VARCHAR,
    track_time_log_is_async           BOOLEAN NOT NULL,
    track_time_log_timestamp          TIMESTAMP WITHOUT TIME ZONE,
    track_time_log_execution_duration BIGINT  NOT NULL
);